package com.diw.practice.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;

/**
 * JPA Entity representing a book in the system.
 * <p>
 * Contains basic book metadata (title, author, ISBN, publication year,
 * publisher) and current status (available, borrowed, reserved). If the book is
 * borrowed, the {@code borrowedBy} relationship references the {@link User} who has it.
 * </p>
 *
 *  
 * @version 1.1
 * @since 1.0
 */
@Entity
@Table(name = "books")
public class Book {

    /**
     * Possible statuses of a book.
     * <ul>
     * <li>{@link #AVAILABLE} — The book is available for loan.</li>
     * <li>{@link #BORROWED} — The book is currently loaned to a user.</li>
     * <li>{@link #RESERVED} — The book is reserved by a user and is not available.</li>
     * </ul>
     */
    public enum Status { AVAILABLE, BORROWED, RESERVED }

    /**
     * Unique identifier generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Title of the book.
     */
    private String title;

    /**
     * Author or authors of the book.
     */
    private String author;

    /**
     * ISBN code of the book.
     */
    private String isbn;

    /**
     * Year of publication.
     */
    private Integer publicationYear;

    /**
     * Publisher responsible for the publication.
     */
    private String publisher;

    /**
     * Current status of the book.
     * <p>
     * Persisted as a string in the database using {@link EnumType#STRING}.
     * </p>
     */
    @Enumerated(EnumType.STRING)
    private Status status = Status.AVAILABLE;

    /**
     * User to whom the book is loaned.
     * <p>
     * Many-to-one relationship with the {@link User} entity. {@link FetchType#LAZY}
     * is used to avoid loading the user until necessary.
     * </p>
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    @JsonBackReference(value = "user-books")
    private User borrowedBy;

    /**
     * Default constructor required by JPA.
     */
    public Book() {
    }

    /**
     * Constructs a {@code Book} instance with primary data.
     *
     * @param title           book title
     * @param author          book author(s)
     * @param isbn            ISBN code
     * @param publicationYear year of publication
     * @param publisher       book publisher
     * @param status          initial status of the book
     */
    public Book(
            String title,
            String author,
            String isbn,
            Integer publicationYear,
            String publisher,
            Status status
    ) {
        this.title = title;
        this.author = author;
        this.isbn = isbn;
        this.publicationYear = publicationYear;
        this.publisher = publisher;
        this.status = status;
    }

    /**
     * Gets the unique identifier of the book.
     *
     * @return book id, may be {@code null} if not yet persisted
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the book identifier.
     * <p>
     * In most cases, this value is managed by JPA and should not be manually assigned.
     * </p>
     *
     * @param id identifier to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Gets the title of the book.
     *
     * @return book title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the title of the book.
     *
     * @param title title to set
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Gets the author of the book.
     *
     * @return book author
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the author of the book.
     *
     * @param author author to set
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * Gets the ISBN of the book.
     *
     * @return book ISBN
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * Sets the ISBN of the book.
     *
     * @param isbn ISBN to set
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     * Gets the publication year.
     *
     * @return publication year, or {@code null} if not specified
     */
    public Integer getPublicationYear() {
        return publicationYear;
    }

    /**
     * Sets the publication year.
     *
     * @param publicationYear year to set
     */
    public void setPublicationYear(Integer publicationYear) {
        this.publicationYear = publicationYear;
    }

    /**
     * Gets the publisher of the book.
     *
     * @return book publisher
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * Sets the publisher of the book.
     *
     * @param publisher publisher to set
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    /**
     * Gets the current status of the book.
     *
     * @return book status
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the book status.
     *
     * @param status status to set
     */
    public void setStatus(Status status) {
        this.status = status;
    }

    /**
     * Gets the user to whom the book is loaned.
     *
     * @return user who has the book borrowed, or {@code null} if not borrowed
     */
    public User getBorrowedBy() {
        return borrowedBy;
    }

    /**
     * Sets the user to whom the book is loaned.
     *
     * @param borrowedBy borrower user, or {@code null} to indicate it is not borrowed
     */
    public void setBorrowedBy(User borrowedBy) {
        this.borrowedBy = borrowedBy;
    }
}