package com.diw.practice.model;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;

import java.util.*;

/**
 * JPA Entity representing a system user.
 * <p>
 * A {@code User} has a unique identifier generated by the database,
 * a name, a role (ADMIN, TEACHER, or STUDENT), and a list of associated
 * books that have been loaned to this user.
 * </p>
 *
 *  
 * @since 1.0
 */
@Entity
@Table(name = "users")
public class User {

    /**
     * Unique identifier of the user.
     * <p>
     * Automatically generated using the {@link GenerationType#IDENTITY} strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Name of the user.
     */
    private String name;

    /**
     * User roles in the system.
     */
    public enum Role { ADMIN, TEACHER, STUDENT }

    /**
     * Role mapping in the database as a string.
     */
    @Enumerated(EnumType.STRING)
    private Role role;

    /**
     * List of books loaned to this user.
     * <p>
     * Bidirectional One-To-Many relationship with the {@code Book} entity.
     * The {@code mappedBy = "borrowedBy"} attribute indicates that the inverse entity maintains the relationship.
     * {@link CascadeType#ALL} is used to propagate persistence operations.
     * The list is initialized to avoid {@link NullPointerException}.
     * </p>
     */
    @OneToMany(mappedBy = "borrowedBy", cascade = CascadeType.ALL)
    @JsonManagedReference(value = "user-books")
    private List<Book> books = new ArrayList<>();

    /**
     * Default constructor required by JPA.
     */
    public User() {}

    /**
     * Constructor with relevant fields (except the books list).
     *
     * @param id     User identifier (can be {@code null} if creating a new one)
     * @param name   User name
     * @param role   User role
     */
    public User(Integer id, String name, Role role) {
        this.id = id;
        this.name = name;
        this.role = role;
    }

    /**
     * Gets the user identifier.
     *
     * @return the user id, or {@code null} if not established
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the user identifier.
     *
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Gets the user name.
     *
     * @return the user name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the user name.
     *
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the user role.
     *
     * @return the user role
     */
    public Role getRole() {
        return role;
    }

    /**
     * Sets the user role.
     *
     * @param role the role to set
     */
    public void setRole(Role role) {
        this.role = role;
    }

    /**
     * Gets the list of books loaned to this user.
     *
     * @return the list of books (never {@code null})
     */
    public List<Book> getBooks() {
        return books;
    }

    /**
     * Replaces the list of books loaned to this user.
     *
     * @param books new list of books (if {@code null} is passed, it initializes as an empty list)
     */
    public void setBooks(List<Book> books) {
        this.books = books != null ? books : new ArrayList<>();
    }
}